//
// Created by JYSimilar on 2022/12/6.
//

#ifndef RM2023_BIGDICKENERGY_DEFINE_H
#define RM2023_BIGDICKENERGY_DEFINE_H


// #define DETECT_BLUE
#define DETECT_RED

#endif //RM2023_BIGDICKENERGY_DEFINE_H
